name: Build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    Debug:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install libsdl2-dev
            - name: Dependency Information
              run: |
                echo "gcc `gcc --version | grep gcc | awk '{print $3}'`"
            - name: Build Debug
              run: |
                make debug
              env:
                CC: gcc
    Release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install libsdl2-dev
            - name: Dependency Information
              run: |
                echo "gcc `gcc --version | grep gcc | awk '{print $3}'`"
            - name: Build Release
              run: |
                make release
              env:
                CC: gcc
