name: Test

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    Debug:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: |
                sudo apt-get update
            - name: Dependency Information
              run: |
                echo "gcc `gcc --version | grep gcc | awk '{print $3}'`"
            - name: Test Debug
              run: |
                make test-debug
              env:
                CC: gcc
    Release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: |
                sudo apt-get update
            - name: Dependency Information
              run: |
                echo "gcc `gcc --version | grep gcc | awk '{print $3}'`"
            - name: Test Release
              run: |
                make test-release
              env:
                CC: gcc
